#!/usr/bin/env tsx
// Single source for the runtime contract ABI surface of this package: the
// constants below are regenerated from the current forge artifacts of
// contracts/uvp-contracts, never hand-copied. Rerun this script after any
// contract change (forge build first), then review the diff.
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { toEventHash, type Hex } from "viem";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageDir = resolve(scriptDir, "..");
const contractsDir = resolve(packageDir, "../../contracts/uvp-contracts");

interface FoundryArtifact {
  readonly abi: readonly unknown[];
}

const stateMachineArtifactPath = resolve(
  contractsDir,
  "out/UVPStateMachine.sol/UVPStateMachine.json",
);
const stateMachineSourcePath = resolve(
  contractsDir,
  "src/UVPStateMachine.sol",
);

interface FlagConstantSpec {
  readonly name: string;
}

// The flags bit values live in the contract source as `uint8 public constant`
// declarations; they are not recoverable from the artifact ABI alone.
const flagConstants: readonly FlagConstantSpec[] = [
  { name: "HOOK_FLAG_ORDER_TRIGGER_MINT" },
  { name: "HOOK_FLAG_ORDER_TRIGGER_DOCK" },
  { name: "HOOK_FLAG_EMIT_READY" },
];

const signalSubmittedEventName = "SignalSubmitted";

async function main(): Promise<void> {
  const artifact = JSON.parse(
    await readFile(stateMachineArtifactPath, "utf8"),
  ) as FoundryArtifact;
  const source = await readFile(stateMachineSourcePath, "utf8");

  const abiJson = JSON.stringify(artifact.abi, null, 2);
  const signalSubmitted = artifact.abi.find(
    (item) =>
      typeof item === "object" &&
      item !== null &&
      (item as { type?: unknown }).type === "event" &&
      (item as { name?: unknown }).name === signalSubmittedEventName,
  );
  if (!signalSubmitted) {
    throw new Error(
      `${signalSubmittedEventName} event missing from ${stateMachineArtifactPath}`,
    );
  }
  const signalSubmittedSignature = eventSignature(signalSubmitted);
  const signalSubmittedTopic: Hex = toEventHash(signalSubmittedSignature);

  const flagLines = flagConstants.map((spec) => {
    const value = extractUintConstant(source, spec.name);
    return `export const ${spec.name} = ${value};`;
  });

  const output = `// Generated by scripts/generate-artifact-abis.ts from the forge artifacts
// and Solidity source of contracts/uvp-contracts; do not edit by hand —
// rerun the generator instead.
import type { Hex } from "viem";

export const UVP_STATE_MACHINE_ARTIFACT_ABI = ${abiJson} as const;

// Single-event ABI slices so consumers can decode one log topic without
// importing the full artifact ABI.
export const SIGNAL_SUBMITTED_ABI = ${JSON.stringify([signalSubmitted], null, 2)} as const;
export const SIGNAL_SUBMITTED_TOPIC = "${signalSubmittedTopic}" as Hex;

${flagLines.join("\n")}
`;

  await writeFile(
    resolve(packageDir, "src/artifact-abis.ts"),
    output,
  );
  console.log(
    `wrote src/artifact-abis.ts (${artifact.abi.length} ABI entries, ${signalSubmittedTopic})`,
  );
}

function eventSignature(event: unknown): string {
  const record = event as {
    readonly name?: unknown;
    readonly inputs?: readonly {
      readonly type?: unknown;
      readonly components?: readonly unknown[];
    }[];
  };
  const inputs = (record.inputs ?? []).map(abiInputType).join(",");
  return `${String(record.name)}(${inputs})`;
}

function abiInputType(input: {
  readonly type?: unknown;
  readonly components?: readonly unknown[];
}): string {
  const type = String(input.type);
  if (!type.startsWith("tuple")) {
    return type;
  }
  const suffix = type.slice("tuple".length);
  const components = (input.components ?? [])
    .map((component) => abiInputType(component as never))
    .join(",");
  return `(${components})${suffix}`;
}

function extractUintConstant(source: string, name: string): number {
  const match = source.match(
    new RegExp(`uint8\\s+public\\s+constant\\s+${name}\\s*=\\s*(\\d+)\\s*;`),
  );
  if (!match?.[1]) {
    throw new Error(`constant ${name} not found in UVPStateMachine.sol`);
  }
  return Number(match[1]);
}

main().catch((error: unknown) => {
  console.error(
    error instanceof Error ? `${error.name}: ${error.message}` : String(error),
  );
  process.exitCode = 1;
});
