#!/usr/bin/env tsx
// Single source for the runtime contract ABI surface of this package: the
// constants below are regenerated from the current forge artifacts of
// contracts/uvp-contracts, never hand-copied. Rerun this script after any
// contract change (forge build first), then review the diff.
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { toEventHash, type Hex } from "viem";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageDir = resolve(scriptDir, "..");
const contractsDir = resolve(packageDir, "../../contracts/uvp-contracts");

interface FoundryArtifact {
  readonly abi: readonly unknown[];
}

const stateMachineArtifactPath = resolve(
  contractsDir,
  "out/UVPStateMachine.sol/UVPStateMachine.json",
);
// finalizePlan 的规模闸错误声明在 IUVPPlanMetadataModule（注册库经接口
// 限定名 revert），因此永远不会出现在 UVPStateMachine 的 artifact ABI 里；
// 镜像只能从接口产物提取。
const planMetadataInterfaceArtifactPath = resolve(
  contractsDir,
  "out/IUVPPlanMetadataModule.sol/IUVPPlanMetadataModule.json",
);
// Single declaration point shared by UVPStateMachine and the linked
// UVPPlanRegistration library; the flags bit values are not recoverable
// from the artifact ABI alone.
const constantsSourcePath = resolve(
  contractsDir,
  "src/UVPStateMachineConstants.sol",
);

interface FlagConstantSpec {
  readonly name: string;
}

const flagConstants: readonly FlagConstantSpec[] = [
  { name: "_HOOK_FLAG_ORDER_TRIGGER_MINT" },
  { name: "_HOOK_FLAG_ORDER_TRIGGER_DOCK" },
  { name: "_HOOK_FLAG_EMIT_READY" },
];

const signalSubmittedEventName = "SignalSubmitted";

// finalizePlan revert 解码面：消费方用 UVP_STATE_MACHINE_ARTIFACT_ABI +
// 本切片才能把规模闸 revert 解出错误名（见生成文件内的注释）。
const finalizePlanErrorNames: readonly string[] = [
  "TooManySelectorBindings",
  "TooManySignalCapabilities",
];

async function main(): Promise<void> {
  const artifact = JSON.parse(
    await readFile(stateMachineArtifactPath, "utf8"),
  ) as FoundryArtifact;
  const constantsSource = await readFile(constantsSourcePath, "utf8");
  const planMetadataInterfaceArtifact = JSON.parse(
    await readFile(planMetadataInterfaceArtifactPath, "utf8"),
  ) as FoundryArtifact;

  const abiJson = JSON.stringify(artifact.abi, null, 2);
  const signalSubmitted = artifact.abi.find(
    (item) =>
      typeof item === "object" &&
      item !== null &&
      (item as { type?: unknown }).type === "event" &&
      (item as { name?: unknown }).name === signalSubmittedEventName,
  );
  if (!signalSubmitted) {
    throw new Error(
      `${signalSubmittedEventName} event missing from ${stateMachineArtifactPath}`,
    );
  }
  const signalSubmittedSignature = eventSignature(signalSubmitted);
  const signalSubmittedTopic: Hex = toEventHash(signalSubmittedSignature);
  const finalizePlanErrors = finalizePlanErrorNames.map((name) => {
    const entry = planMetadataInterfaceArtifact.abi.find(
      (item) =>
        typeof item === "object" &&
        item !== null &&
        (item as { type?: unknown }).type === "error" &&
        (item as { name?: unknown }).name === name,
    );
    if (!entry) {
      throw new Error(
        `error ${name} missing from ${planMetadataInterfaceArtifactPath}`,
      );
    }
    return entry;
  });

  const flagLines = flagConstants.map((spec) => {
    const value = extractUintConstant(constantsSource, spec.name);
    return `export const ${spec.name.slice(1)} = ${value};`;
  });

  const output = `// Generated by scripts/generate-artifact-abis.ts from the forge artifacts
// and Solidity source of contracts/uvp-contracts; do not edit by hand —
// rerun the generator instead.
import type { Hex } from "viem";

export const UVP_STATE_MACHINE_ARTIFACT_ABI = ${abiJson} as const;

// Single-event ABI slices so consumers can decode one log topic without
// importing the full artifact ABI.
export const SIGNAL_SUBMITTED_ABI = ${JSON.stringify([signalSubmitted], null, 2)} as const;
export const SIGNAL_SUBMITTED_TOPIC = "${signalSubmittedTopic}" as Hex;

// finalizePlan revert 解码面：TooManySelectorBindings /
// TooManySignalCapabilities 声明在 IUVPPlanMetadataModule 上，由
// UVPStateMachine 经链接注册库在 finalizePlan 边界 revert——它们不在
// UVPStateMachine 自身的 artifact ABI 里，解码 finalizePlan revert 时必须
// 把本切片并入 UVP_STATE_MACHINE_ARTIFACT_ABI，否则错误名匹配不到。
export const FINALIZE_PLAN_ERRORS_ABI = ${JSON.stringify(finalizePlanErrors, null, 2)} as const;

${flagLines.join("\n")}
`;

  await writeFile(
    resolve(packageDir, "src/artifact-abis.ts"),
    output,
  );
  console.log(
    `wrote src/artifact-abis.ts (${artifact.abi.length} ABI entries, ${signalSubmittedTopic}, ${finalizePlanErrors.length} finalizePlan errors)`,
  );
}

function eventSignature(event: unknown): string {
  const record = event as {
    readonly name?: unknown;
    readonly inputs?: readonly {
      readonly type?: unknown;
      readonly components?: readonly unknown[];
    }[];
  };
  const inputs = (record.inputs ?? []).map(abiInputType).join(",");
  return `${String(record.name)}(${inputs})`;
}

function abiInputType(input: {
  readonly type?: unknown;
  readonly components?: readonly unknown[];
}): string {
  const type = String(input.type);
  if (!type.startsWith("tuple")) {
    return type;
  }
  const suffix = type.slice("tuple".length);
  const components = (input.components ?? [])
    .map((component) => abiInputType(component as never))
    .join(",");
  return `(${components})${suffix}`;
}

function extractUintConstant(source: string, name: string): number {
  const match = source.match(
    new RegExp(`uint8\\s+(?:public\\s+)?constant\\s+${name}\\s*=\\s*(\\d+)\\s*;`),
  );
  if (!match?.[1]) {
    throw new Error(`constant ${name} not found in UVPStateMachineConstants.sol`);
  }
  return Number(match[1]);
}

main().catch((error: unknown) => {
  console.error(
    error instanceof Error ? `${error.name}: ${error.message}` : String(error),
  );
  process.exitCode = 1;
});
