export { canonicalize, canonicalStringify } from "./canonical.js";
export {
  assertHookPlanArtifact,
  compileZhixuHookPlan,
  HookPlanCompilationError,
  HookPlanArtifactValidationError,
  validateHookPlanArtifact,
} from "./hook-plan.js";
export {
  loadZhixuDefinition,
  parseZhixuDefinition,
  ZhixuLoadError,
} from "./zhixu-loader.js";
export {
  assertOnchainHookPlanArtifact,
  compileZhixuOnchainHookPlan,
  compileZhixuRegisterPlanArgs,
  hashSolidityRegisterHooks,
  onchainHookId,
  onchainHookName,
  planIdForPublisher,
  onchainSelectorBindingHash,
  onchainSignalId,
  onchainSignalKey,
  onchainSourceId,
  onchainStageId,
  OnchainHookPlanArtifactValidationError,
  toSolidityRegisterPlanArgs,
  validateOnchainHookPlanArtifact,
} from "./onchain-hook-plan.js";
export { hashCanonical, keccak256Hex } from "./hash.js";
export {
  canonicalSignalHash,
  cloudRuntimeDomain,
  definitionRefHash,
  definitionUid,
  displayIdentity,
  dockInstanceId,
  dockInputPayloadHash,
  dockOutputIdempotencyKey,
  dockInputIdempotencyKey,
  dockRouteId,
  dockRoutesRootOf,
  EMPTY_MERKLE_ROOT,
  eip712PermitDigest,
  eip712PermitDomainSeparator,
  eip712PermitStructHash,
  evmRuntimeDomain,
  hookKey,
  inputBindingHash,
  inputPortLeaf,
  interfaceLeaf,
  interfaceNameKey,
  interfaceRootOf,
  linkedOrderId,
  localOrderKey,
  MAX_CHAIN_ID,
  merkleProof,
  merkleRoot,
  modeWord,
  orderModesWord,
  outputBindingHash,
  outputPortLeaf,
  PERMIT_DOMAIN_NAME,
  PERMIT_DOMAIN_TYPE,
  PERMIT_DOMAIN_VERSION,
  PERMIT_TYPEHASH,
  portKey,
  requireChainId,
  routeHash,
  sourceFactSetHash,
  stageKey,
  stripAnnotations,
  targetOrderRefKey,
  u64Word,
  verifyMerkleProof,
} from "./dock.js";
// dock hash 域常量族（UVP_DOCK_*_V2 + 沿用的 V1 域）：兼容矩阵冻结的
// 版本族断言消费（golden fixtures/dock/v1/manifest.json constants.domains）。
export {
  DEFINITION_UID_DOMAIN,
  DOCK_ORDER_NAMESPACE_MASK,
  DOMAIN_DEFINITION_REF,
  DOMAIN_INTERFACE,
  DOMAIN_INTERFACE_INPUT,
  DOMAIN_INTERFACE_OUTPUT,
  DOMAIN_ROUTE_ID,
  DOMAIN_INPUT_BINDING,
  DOMAIN_OUTPUT_BINDING,
  DOMAIN_ROUTE,
  DOMAIN_DOCK_INSTANCE,
  DOMAIN_DOCK_ORDER,
  DOMAIN_INPUT_PAYLOAD,
} from "./dock.js";
export {
  HOOK_FLAG_EMIT_READY,
  HOOK_FLAG_ORDER_TRIGGER_DOCK,
  HOOK_FLAG_ORDER_TRIGGER_MINT,
  solidityHookFlags,
} from "./onchain-hook-plan.js";
export {
  COMPILER_NAME,
  COMPILER_VERSION,
  HOOK_PLAN_SCHEMA_VERSION,
  ONCHAIN_HOOK_PLAN_SCHEMA_VERSION,
  DOCK_INTERFACE_ARTIFACT_SCHEMA_VERSION,
  DOCK_ROUTE_SCHEMA_VERSION,
  DOCK_RESOLUTION_SCHEMA_VERSION,
} from "./types/index.js";
export type {
  Address,
  DockInterfaceArtifactInterface,
  DockInterfaceArtifactPortInput,
  DockInterfaceArtifactPortOutput,
  DockInterfaceArtifactV2,
  DockInterfaceSource,
  DockInterfaceSpecSource,
  DockOrderMode,
  DockResolutionManifest,
  DockResolutionTarget,
  DockRouteInputBinding,
  DockRouteOutputBinding,
  DockRouteV2,
  ExecuteConfigs,
  OrderTriggerKind,
  FileResourceLike,
  HexString,
  ObjectMeta,
  OnchainCompiledHook,
  OnchainDelayInstruction,
  OnchainExecutorRoute,
  OnchainExecutorRouteRef,
  OnchainHookDependency,
  OnchainHookInstruction,
  OnchainHookPlanArtifact,
  OnchainJoinInstruction,
  OnchainSignalCapability,
  OnchainSignalInstruction,
  OnchainStageSelectorBinding,
  OnchainUnaryInstruction,
  SignalTargetOrderRelation,
  SolidityRegisterDependencyIndexArg,
  SolidityRegisterExecutorRouteArg,
  SolidityRegisterHookArg,
  SolidityRegisterInstructionArg,
  SolidityRegisterPlanArgs,
  SolidityRegisterSignalCapabilityArg,
  SolidityRegisterStageSelectorBindingArg,
  ZhixuDefinition,
  ZhixuExecutorConfigSource,
  ZhixuPlatform,
  ZhixuStage,
  ZhixuTaskPattern,
} from "./types/index.js";
