// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {UVPPlanMetadataModule} from "../src/UVPPlanMetadataModule.sol";
import {DockMerkle} from "../src/libraries/DockMerkle.sol";

/// @dev The test suite intentionally keeps its own narrow Vm interface so it
/// does not need to vendor forge-std just to consume the compiler fixture.
interface CapabilitiesRootVm {
    function projectRoot() external view returns (string memory);
    function readFile(string calldata path) external view returns (string memory);
    function parseJsonBytes32(string calldata json, string calldata key) external view returns (bytes32);
    function parseJsonUint(string calldata json, string calldata key) external view returns (uint256);
}

/// @title Solidity/TypeScript capabilitiesRoot equality gate
/// @notice Reads the canonical golden fixture generated by the chain-track TS
///         authority (packages/compiler generate:capabilities-root-fixtures)
///         and recomputes every leaf/root/proof consumed by
///         UVPPlanMetadataModule：能力叶/绑定叶公式（真实合约代码重算）、
///         双表混编排序去重建树（DockMerkle）、成员资格证明验证。TS 侧
///         capabilities-root-golden.test.ts 消费同一份 fixture——两侧任何
///         一方漂移都会在至少一侧响亮失配。
contract CapabilitiesRootParityTest {
    CapabilitiesRootVm private constant vm =
        CapabilitiesRootVm(address(uint160(uint256(keccak256("hevm cheat code")))));

    function _fixture() private view returns (string memory) {
        return
            vm.readFile(string.concat(vm.projectRoot(), "/../../packages/compiler/fixtures/capabilities-root/v1/vectors.json"));
    }

    function _sample(uint256 sample) private pure returns (string memory) {
        require(sample < GOLDEN_SAMPLE_COUNT, "capabilities-root golden sample out of range");
        return string.concat(".samples[", toString(sample), "]");
    }

    function _count(string memory json, string memory base) private view returns (uint256) {
        return vm.parseJsonUint(json, base);
    }

    /// forge 侧 vm.parseJson 不支持 .length 路径，样本数、每样本计数与每
    /// 条证明长度都从 fixture 的镜像字段读取（TS 测试断言计数与实际数组
    /// 长一致）。
    uint256 private constant GOLDEN_SAMPLE_COUNT = 2;

    function testMixedTablesOddLeavesSampleMatches() public {
        _assertSampleMatches(0);
    }

    function testDuplicateLeavesDedupSampleMatches() public {
        _assertSampleMatches(1);
    }

    /// 每个样本：叶公式（合约实现）重算 == pinned 叶；root（DockMerkle
    /// 建树）== pinned root；pinned 证明对 root 验证通过；pinned
    /// sortedUniqueLeaves 严格升序且其树根与原始输入建树一致（钉排序
    /// 去重语义）。
    function _assertSampleMatches(uint256 sampleIndex) private {
        string memory fixture = _fixture();
        string memory sample = _sample(sampleIndex);
        UVPPlanMetadataModule metadataModule = new UVPPlanMetadataModule(address(0));

        uint256 bindingCount = _count(fixture, string.concat(sample, ".counts.selectorBindings"));
        uint256 capabilityCount = _count(fixture, string.concat(sample, ".counts.signalCapabilities"));
        require(bindingCount > 0 && capabilityCount > 0, "capabilities-root golden empty sample");

        bytes32 rootValue = vm.parseJsonBytes32(fixture, string.concat(sample, ".expected.root"));
        uint256 uniqueCount = _count(fixture, string.concat(sample, ".counts.sortedUniqueLeaves"));

        bytes32[] memory rawLeaves = new bytes32[](bindingCount + capabilityCount);
        uint256 cursor;

        for (uint256 i = 0; i < bindingCount; i++) {
            string memory inputBase = string.concat(sample, ".inputs.selectorBindings[", toString(i), "]");
            string memory expectedBase =
                string.concat(sample, ".expected.selectorBindingLeaves[", toString(i), "]");
            bytes32 leafValue = metadataModule.selectorBindingLeaf(
                vm.parseJsonBytes32(fixture, string.concat(inputBase, ".selectorStageId")),
                vm.parseJsonBytes32(fixture, string.concat(inputBase, ".targetStageId"))
            );
            _assertLeafAndProof(fixture, rootValue, leafValue, expectedBase);
            rawLeaves[cursor++] = leafValue;
        }

        for (uint256 i = 0; i < capabilityCount; i++) {
            string memory inputBase = string.concat(sample, ".inputs.signalCapabilities[", toString(i), "]");
            string memory expectedBase =
                string.concat(sample, ".expected.signalCapabilityLeaves[", toString(i), "]");
            bytes32 leafValue = metadataModule.signalCapabilityLeaf(
                vm.parseJsonBytes32(fixture, string.concat(inputBase, ".stageId")),
                vm.parseJsonBytes32(fixture, string.concat(inputBase, ".targetSourceId")),
                vm.parseJsonBytes32(fixture, string.concat(inputBase, ".signalId")),
                uint8(vm.parseJsonUint(fixture, string.concat(inputBase, ".targetOrderRelation")))
            );
            _assertLeafAndProof(fixture, rootValue, leafValue, expectedBase);
            rawLeaves[cursor++] = leafValue;
        }

        // 原始输入（含重复叶）建树 == pinned root：排序去重在树内完成。
        require(DockMerkle.root(rawLeaves) == rootValue, "capabilities-root golden root mismatch");

        // pinned 排序去重叶集：严格升序，且与原始输入建出同一棵树。
        bytes32[] memory uniqueLeaves = new bytes32[](uniqueCount);
        for (uint256 i = 0; i < uniqueCount; i++) {
            uniqueLeaves[i] =
                vm.parseJsonBytes32(fixture, string.concat(sample, ".expected.sortedUniqueLeaves[", toString(i), "]"));
            if (i > 0) {
                require(uniqueLeaves[i - 1] < uniqueLeaves[i], "capabilities-root golden leaves not strictly ascending");
            }
        }
        require(DockMerkle.root(uniqueLeaves) == rootValue, "capabilities-root golden unique-leaf root mismatch");
    }

    function _assertLeafAndProof(
        string memory fixture,
        bytes32 rootValue,
        bytes32 leafValue,
        string memory expectedBase
    ) private view {
        require(leafValue == vm.parseJsonBytes32(fixture, string.concat(expectedBase, ".leaf")), "leaf mismatch");
        uint256 proofLength = _count(fixture, string.concat(expectedBase, ".proofLength"));
        bytes32[] memory proof = new bytes32[](proofLength);
        for (uint256 i = 0; i < proofLength; i++) {
            proof[i] = vm.parseJsonBytes32(fixture, string.concat(expectedBase, ".proof[", toString(i), "]"));
        }
        require(DockMerkle.verify(rootValue, leafValue, proof), "proof does not verify against root");
    }

    function toString(uint256 value) private pure returns (string memory) {
        if (value == 0) {
            return "0";
        }
        uint256 buffer = value;
        uint256 digits;
        while (buffer != 0) {
            digits++;
            buffer /= 10;
        }
        bytes memory result = new bytes(digits);
        uint256 index = digits;
        buffer = value;
        while (buffer != 0) {
            index--;
            result[index] = bytes1(uint8(48 + (buffer % 10)));
            buffer /= 10;
        }
        return string(result);
    }
}
