// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @dev The test suite intentionally keeps its own narrow Vm interface so it
/// does not need to vendor forge-std just to consume the Rust fixture.
interface DockManifestVm {
    function projectRoot() external view returns (string memory);
    function readFile(string calldata path) external view returns (string memory);
    function parseJsonAddress(string calldata json, string calldata key) external view returns (address);
    function parseJsonBytes32(string calldata json, string calldata key) external view returns (bytes32);
    function parseJsonString(string calldata json, string calldata key) external view returns (string memory);
    function parseJsonUint(string calldata json, string calldata key) external view returns (uint256);
}

import {DockMerkle} from "../src/libraries/DockMerkle.sol";

/// @title Rust/Go/TypeScript/Solidity dock manifest equality gate
/// @notice Reads the canonical manifest generated by uvp-core and recomputes
///         the EVM word encodings used by UVPDockingModule. This prevents the
///         Solidity side from silently retaining a copied or stale vector.
contract DockManifestParityTest {
    DockManifestVm private constant vm = DockManifestVm(address(uint160(uint256(keccak256("hevm cheat code")))));

    bytes32 private constant DOMAIN_DOCK_INSTANCE = keccak256("UVP_DOCK_INSTANCE_V1");
    bytes32 private constant DOMAIN_DOCK_ORDER = keccak256("UVP_DOCK_ORDER_V1");
    bytes32 private constant DOCK_ORDER_NAMESPACE_MASK = bytes32(uint256(1) << 255);
    bytes32 private constant DOMAIN_RUNTIME_CLOUD = keccak256("UVP_RUNTIME_CLOUD_V1");
    bytes32 private constant DOMAIN_RUNTIME_EIP155 = keccak256("UVP_RUNTIME_EIP155_V1");
    bytes32 private constant DOMAIN_DEFINITION_REF = keccak256("UVP_DEFINITION_REF_V1");

    function assertEq(bytes32 left, bytes32 right) internal pure {
        if (left != right) {
            revert("dock manifest bytes32 mismatch");
        }
    }

    function assertEq(string memory left, string memory right) internal pure {
        if (keccak256(bytes(left)) != keccak256(bytes(right))) {
            revert("dock manifest string mismatch");
        }
    }

    function testSharedDockManifestMatchesSolidityPreimages() public {
        string memory manifest =
            vm.readFile(string.concat(vm.projectRoot(), "/../../../uvp-core/fixtures/dock/v1/manifest.json"));

        uint256 chainId = vm.parseJsonUint(manifest, ".inputs.chainId");
        address stateMachine = vm.parseJsonAddress(manifest, ".inputs.stateMachineAddress");
        bytes32 stateMachineWord = bytes32(uint256(uint160(stateMachine)));
        bytes32 expectedEvmDomain = vm.parseJsonBytes32(manifest, ".expected.evmRuntimeDomain");
        assertEq(keccak256(abi.encode(DOMAIN_RUNTIME_EIP155, chainId, stateMachineWord)), expectedEvmDomain);

        string memory cloudDeployment = vm.parseJsonString(manifest, ".inputs.cloudDeploymentId");
        string memory cloudSecurityDomain = vm.parseJsonString(manifest, ".inputs.cloudSecurityDomain");
        bytes32 expectedCloudDomain = vm.parseJsonBytes32(manifest, ".expected.cloudRuntimeDomain");
        assertEq(
            keccak256(
                abi.encode(
                    DOMAIN_RUNTIME_CLOUD, keccak256(bytes(cloudDeployment)), keccak256(bytes(cloudSecurityDomain))
                )
            ),
            expectedCloudDomain
        );

        string memory parentUid = vm.parseJsonString(manifest, ".parentDefinition.metadata.uid");
        string memory parentVersion = vm.parseJsonString(manifest, ".parentDefinition.metadata.annotations.version");
        bytes32 parentDefinitionRef =
            keccak256(abi.encode(DOMAIN_DEFINITION_REF, keccak256(bytes(parentUid)), keccak256(bytes(parentVersion))));
        assertEq(parentDefinitionRef, vm.parseJsonBytes32(manifest, ".expected.parentDefinitionRefHash"));

        string memory targetUid = vm.parseJsonString(manifest, ".targetDefinition.metadata.uid");
        string memory targetVersion = vm.parseJsonString(manifest, ".targetDefinition.metadata.annotations.version");
        bytes32 targetDefinitionRef =
            keccak256(abi.encode(DOMAIN_DEFINITION_REF, keccak256(bytes(targetUid)), keccak256(bytes(targetVersion))));
        assertEq(targetDefinitionRef, vm.parseJsonBytes32(manifest, ".expected.targetDefinitionRefHash"));

        // localOrderKey 的字符串→word 哈希是跨语言 v1 入口 API 的固定派生
        // 规则（Rust local_order_key / TS localOrderKey：字符串 orderID 先
        // 哈希成 word，order.idPolicy=derived-v1）。合约本身消费的是 word
        // 本身：openDockedOrder 的 localOrderId 参数裸用，不做二次哈希
        // （EVM 轨订单键即 word）——manifest 的 expected 值钉的是入口 API
        // 派生，合约编码由 UVPDockingModule.t.sol 的 word 用例单独钉住。
        string memory localOrderId = vm.parseJsonString(manifest, ".inputs.localOrderId");
        bytes32 localOrderKey = keccak256(bytes(localOrderId));
        assertEq(localOrderKey, vm.parseJsonBytes32(manifest, ".expected.localOrderKey"));

        bytes32 parentPlanId = vm.parseJsonBytes32(manifest, ".inputs.parentPlanIdWord");
        bytes32 routeId = vm.parseJsonBytes32(manifest, ".expected.dockRoutes[0].routeId");
        bytes32 routeHash = vm.parseJsonBytes32(manifest, ".expected.dockRoutes[0].routeHash");
        bytes32 dockInstanceId = keccak256(
            abi.encode(
                DOMAIN_DOCK_INSTANCE,
                expectedEvmDomain,
                parentPlanId,
                parentDefinitionRef,
                localOrderKey,
                routeId,
                routeHash
            )
        );
        assertEq(dockInstanceId, vm.parseJsonBytes32(manifest, ".expected.dockInstanceId"));

        bytes32 linkedOrderId = bytes32(
            uint256(keccak256(abi.encode(DOMAIN_DOCK_ORDER, dockInstanceId, targetDefinitionRef)))
                | uint256(DOCK_ORDER_NAMESPACE_MASK)
        );
        assertEq(linkedOrderId, vm.parseJsonBytes32(manifest, ".expected.linkedOrderId"));
    }

    /// ETH-7：root 排序去重在函数内拷贝上执行——调用方数组在调用前后
    /// 逐字节不变（含长度），不得被就地截断。
    function testMerkleRootDoesNotMutateCallerArray() public {
        bytes32[] memory leaves = new bytes32[](5);
        leaves[0] = bytes32(uint256(0xC));
        leaves[1] = bytes32(uint256(0xA));
        leaves[2] = bytes32(uint256(0xA)); // 重复叶
        leaves[3] = bytes32(uint256(0xB));
        leaves[4] = bytes32(uint256(0xD));
        bytes32[] memory snapshot = new bytes32[](5);
        for (uint256 i = 0; i < leaves.length; i++) {
            snapshot[i] = leaves[i];
        }
        bytes32 rootValue = DockMerkle.root(leaves);
        require(leaves.length == 5, "caller array length mutated");
        for (uint256 i = 0; i < leaves.length; i++) {
            assertEq(leaves[i], snapshot[i]);
        }
        // 去重排序后的根与手工树一致（A、B、C、D 四叶）。
        bytes32[] memory sorted = new bytes32[](4);
        sorted[0] = bytes32(uint256(0xA));
        sorted[1] = bytes32(uint256(0xB));
        sorted[2] = bytes32(uint256(0xC));
        sorted[3] = bytes32(uint256(0xD));
        assertEq(rootValue, DockMerkle.root(sorted));
    }
}
