// Generated by scripts/generate-artifact-abis.ts from the forge artifacts
// and Solidity source of contracts/uvp-contracts; do not edit by hand —
// rerun the generator instead.
import type { Hex } from "viem";

export const UVP_STATE_MACHINE_ARTIFACT_ABI = [
  {
    "type": "constructor",
    "inputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "DERIVED_SIGNAL_MODULE_ID",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "DOCKING_MODULE_ID",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "DOCK_ORDER_NAMESPACE_MASK",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "DOMAIN_SEPARATOR",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "HOOK_FLAG_EMIT_READY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "HOOK_FLAG_ORDER_TRIGGER_DOCK",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "HOOK_FLAG_ORDER_TRIGGER_MINT",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "LENS_MODULE_ID",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_HOOK_DELAY_SECONDS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_PLAN_DEPENDENCIES",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ORDER_LINK_MODULE_ID",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "PLAN_METADATA_MODULE_ID",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SIGNAL_TARGET_CURRENT_ORDER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SIGNAL_TARGET_TRIGGER_ORIGIN",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "STAGE_PATCH_MODULE_ID",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "activateStageExecutorFromModule",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "targetStageId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "executor",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "executorMetadataHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "patchHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "patchNonce",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "metadataURI",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "activeStageExecutor",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "targetStageId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "commitPlan",
    "inputs": [
      {
        "name": "commit",
        "type": "tuple",
        "internalType": "struct UVPStateMachine.PlanCommit",
        "components": [
          {
            "name": "publisher",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "hooksHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "metadataHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "dockRoutesRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "dockInterfaceRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "deadline",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "hooks",
        "type": "tuple[]",
        "internalType": "struct UVPStateMachine.CompactHook[]",
        "components": [
          {
            "name": "hookId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "stageId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "hookName",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "flags",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "instructions",
            "type": "tuple[]",
            "internalType": "struct UVPStateMachine.Instruction[]",
            "components": [
              {
                "name": "op",
                "type": "uint8",
                "internalType": "enum UVPStateMachine.InstructionOp"
              },
              {
                "name": "sourceId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "signalId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "arity",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "delaySeconds",
                "type": "uint64",
                "internalType": "uint64"
              }
            ]
          },
          {
            "name": "dependencyKeys",
            "type": "bytes32[]",
            "internalType": "bytes32[]"
          }
        ]
      },
      {
        "name": "signature",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "createDockedOrderFromModule",
    "inputs": [
      {
        "name": "targetPlanId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "linkedOrderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "creator",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "relayer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "entranceHookId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "entranceStageId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "payloadHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "idempotencyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "submitter",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "authorizations",
        "type": "tuple[]",
        "internalType": "struct UVPStateMachine.SignalAuthorization[]",
        "components": [
          {
            "name": "sourceId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "signalId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "submitter",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "role",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "metadataHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "delegateStageExecutorSignalFromModule",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "targetStageId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "executor",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "metadataHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "patchNonce",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "derivedSignalModule",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "dockingModule",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "finalizePlan",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "selectorBindings",
        "type": "tuple[]",
        "internalType": "struct IUVPPlanMetadataModule.StageSelectorBinding[]",
        "components": [
          {
            "name": "selectorStageId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "targetStageId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "signalCapabilities",
        "type": "tuple[]",
        "internalType": "struct IUVPPlanMetadataModule.SignalCapability[]",
        "components": [
          {
            "name": "stageId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "targetSourceId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "signalId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "targetOrderRelation",
            "type": "uint8",
            "internalType": "uint8"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "freezeModules",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getHookStatus",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "hookId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "status",
        "type": "uint8",
        "internalType": "enum UVPStateMachine.HookStatus"
      },
      {
        "name": "dueAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "readyEmitted",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getSignal",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "exists",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "payloadHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "idempotencyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "submittedAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "submitter",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getSignalAuthorization",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "submitter",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "exists",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "metadataHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hasExplicitSignalAuthorization",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "submitter",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hasSignal",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hasSourceSignal",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hasTriggerOriginConsent",
    "inputs": [
      {
        "name": "originPlanId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "originOrderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "originSourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "originSignalId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "party",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isSignalSubmitterAuthorized",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "submitter",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "lastSignalSubmitter",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "submitter",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "lens",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "moduleSetHash",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "modulesFrozen",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "orderCreator",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "orderExists",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "orderLinkModule",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "orderRelayer",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "planCommitted",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "planDockRoots",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "dockRoutesRoot",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "dockInterfaceRoot",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "planExists",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "planFinalized",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "planHash",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "planHookFlags",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "hookId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "planHookStageId",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "hookId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "planIdFor",
    "inputs": [
      {
        "name": "publisher",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "runtimePlanHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "planMetadataModule",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "planPublisher",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "planRuntimeHash",
    "inputs": [
      {
        "name": "hooksHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "metadataHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "dockRoutesRoot",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "dockInterfaceRoot",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "pokeTimer",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "hookId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "recordDockedInputFromModule",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "payloadHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "idempotencyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "submitter",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDerivedSignalModule",
    "inputs": [
      {
        "name": "moduleAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDockingModule",
    "inputs": [
      {
        "name": "moduleAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setLens",
    "inputs": [
      {
        "name": "moduleAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setOrderLinkModule",
    "inputs": [
      {
        "name": "moduleAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setPlanMetadataModule",
    "inputs": [
      {
        "name": "moduleAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setStagePatchModule",
    "inputs": [
      {
        "name": "moduleAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "sourceSignalCount",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "count",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "stagePatchModule",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "submitDerivedSignalFromModule",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "stageId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "payloadHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "idempotencyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "submitter",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "submitSignal",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "payloadHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "idempotencyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "submitSignalFor",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "payloadHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "idempotencyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "submitter",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "deadline",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "signature",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "submitSignalFromModule",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "payloadHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "idempotencyKey",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "submitter",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "triggerOrderFromOutsideFor",
    "inputs": [
      {
        "name": "trigger",
        "type": "tuple",
        "internalType": "struct UVPStateMachine.TriggerOrderFromOutsideRequest",
        "components": [
          {
            "name": "planId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "creator",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "triggerHookId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "triggerStageId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "sourceId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "signalId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "payloadHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "idempotencyKey",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "submitter",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "deadline",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "authorizations",
        "type": "tuple[]",
        "internalType": "struct UVPStateMachine.SignalAuthorization[]",
        "components": [
          {
            "name": "sourceId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "signalId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "submitter",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "role",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "metadataHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "signature",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "triggerOrderFromSignalFromModule",
    "inputs": [
      {
        "name": "trigger",
        "type": "tuple",
        "internalType": "struct UVPStateMachine.TriggerOrderFromSignalRequest",
        "components": [
          {
            "name": "orderId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "planId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "creator",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "triggerOriginOrderId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "originPlanId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "triggerHookId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "triggerStageId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "originSourceId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "originSignalId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "payloadHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "idempotencyKey",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "submitter",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "deadline",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "authorizations",
        "type": "tuple[]",
        "internalType": "struct UVPStateMachine.SignalAuthorization[]",
        "components": [
          {
            "name": "sourceId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "signalId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "submitter",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "role",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "metadataHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "relayer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "triggerOrderIdFor",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "payloadHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "event",
    "name": "HookReady",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "hookId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "stageId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "hookName",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "HookStatusChanged",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "hookId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "previousStatus",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum UVPStateMachine.HookStatus"
      },
      {
        "name": "newStatus",
        "type": "uint8",
        "indexed": false,
        "internalType": "enum UVPStateMachine.HookStatus"
      },
      {
        "name": "dueAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OrderMaterialized",
    "inputs": [
      {
        "name": "orderId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "planId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "stageId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OrderRegistered",
    "inputs": [
      {
        "name": "orderId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "planId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OrderRelayerRecorded",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "relayer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "creator",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OrderTriggered",
    "inputs": [
      {
        "name": "orderId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "planId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "triggerStageId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "submitter",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PlanCommitted",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "planHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "publisher",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "hooksHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "metadataHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "hookCount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "dockRoutesRoot",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "dockInterfaceRoot",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PlanFinalized",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "planHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "metadataHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PlanPublisherRecorded",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "publisher",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PlanRegistered",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "planHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "hookCount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SignalSubmitted",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "payloadHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "idempotencyKey",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "submitter",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SignalSubmitterAuthorized",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "submitter",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "role",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "metadataHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "StageExecutorActivated",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "targetStageId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "executor",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "role",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "metadataHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "patchNonce",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "metadataURI",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "StageExecutorSignalDelegated",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "targetStageId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "executor",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "role",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "metadataHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "patchNonce",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "StageMaterialized",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "stageId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "triggerHookId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "StateMachineModuleSet",
    "inputs": [
      {
        "name": "moduleId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "previousModule",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newModule",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "StateMachineModulesFrozen",
    "inputs": [
      {
        "name": "moduleSetHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TimerPoked",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "hookId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "dueAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "CrossStageDependency",
    "inputs": [
      {
        "name": "signalKey",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "EmptyPlan",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ExpiredPlanSignature",
    "inputs": [
      {
        "name": "deadline",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ExpiredSignalSignature",
    "inputs": [
      {
        "name": "deadline",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "HookAlreadyRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "HookDelayTooLong",
    "inputs": [
      {
        "name": "delaySeconds",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "IncompleteModuleConfiguration",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidDockOrderNamespace",
    "inputs": [
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidHook",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidInstruction",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidModuleAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidPlanSignature",
    "inputs": [
      {
        "name": "expectedSigner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "recoveredSigner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidSignalCapability",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidSignalSignature",
    "inputs": [
      {
        "name": "expectedSigner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "recoveredSigner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidSignalSignatureLength",
    "inputs": [
      {
        "name": "length",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidSignatureS",
    "inputs": [
      {
        "name": "s",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidSignatureV",
    "inputs": [
      {
        "name": "v",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidTriggerHook",
    "inputs": [
      {
        "name": "hookId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidTriggerOrderSignature",
    "inputs": [
      {
        "name": "expectedSigner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "recoveredSigner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ModulesAlreadyFrozen",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ModulesFrozen",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ModulesNotFrozen",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OrderAlreadyRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PlanAlreadyRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PlanMetadataHashMismatch",
    "inputs": [
      {
        "name": "expectedHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "actualHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "PlanNotCommitted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PlanNotFinalized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SignalAlreadyExists",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SignalSubmitterAlreadyAuthorized",
    "inputs": [
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "submitter",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "SilentOrderTriggerHook",
    "inputs": [
      {
        "name": "hookId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "StageExecutorNotAssigned",
    "inputs": [
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "targetStageId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "StageExecutorPatchNonceNotIncreasing",
    "inputs": [
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "targetStageId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "previousNonce",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "patchNonce",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "StageNotMaterializable",
    "inputs": [
      {
        "name": "stageId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "TimerNotDue",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TimerNotWaiting",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TooManyDependencies",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnauthorizedSignalSubmitter",
    "inputs": [
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "submitter",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnauthorizedStageExecutor",
    "inputs": [
      {
        "name": "orderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "targetStageId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "submitter",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "executor",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnauthorizedStateMachineModule",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnauthorizedTriggerOrigin",
    "inputs": [
      {
        "name": "originPlanId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "originOrderId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "submitter",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnknownHook",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownOrder",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownPlan",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroOrderCreator",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroOrderId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroPatchHash",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroPlanPublisher",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroSignalId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroSourceId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroStageExecutor",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroSubmitter",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroTargetStageId",
    "inputs": []
  }
] as const;

// Single-event ABI slices so consumers can decode one log topic without
// importing the full artifact ABI.
export const SIGNAL_SUBMITTED_ABI = [
  {
    "type": "event",
    "name": "SignalSubmitted",
    "inputs": [
      {
        "name": "planId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "orderId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "sourceId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "signalId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "payloadHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "idempotencyKey",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "submitter",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  }
] as const;
export const SIGNAL_SUBMITTED_TOPIC = "0x41c82bf034d8a61d15b79fcac36c465b2655b5bb3f33fb4c16f01c174103acf3" as Hex;

export const HOOK_FLAG_ORDER_TRIGGER_MINT = 1;
export const HOOK_FLAG_ORDER_TRIGGER_DOCK = 2;
export const HOOK_FLAG_EMIT_READY = 4;
